export const TOWN_LAYOUT = {
  width: 32,
  height: 24,
  spawn: { x: 6, y: 15 },
  fountain: { x: 12, y: 12 },
  paths: [
    { x: 0, y: 11, width: 32, height: 2 },
    { x: 11, y: 2, width: 2, height: 22 },
    { x: 4, y: 6, width: 5, height: 2 },
    { x: 19, y: 6, width: 6, height: 2 },
    { x: 22, y: 14, width: 2, height: 6 },
  ],
  decorations: [
    {
      texture: "house",
      x: 6,
      y: 4,
      scale: 1,
      collider: { width: 74, height: 34, offsetY: 18 },
    },
    {
      texture: "house",
      x: 19,
      y: 4,
      scale: 1.08,
      collider: { width: 80, height: 36, offsetY: 18 },
    },
    {
      texture: "house",
      x: 24,
      y: 17,
      scale: 1.04,
      collider: { width: 78, height: 36, offsetY: 18 },
    },
    {
      texture: "tree",
      x: 3,
      y: 3,
      scale: 1.05,
      collider: { width: 26, height: 24, offsetY: 14 },
    },
    {
      texture: "tree",
      x: 2,
      y: 18,
      scale: 1.2,
      collider: { width: 28, height: 26, offsetY: 14 },
    },
    {
      texture: "tree",
      x: 15,
      y: 18,
      scale: 1.1,
      collider: { width: 26, height: 24, offsetY: 14 },
    },
    {
      texture: "tree",
      x: 28,
      y: 7,
      scale: 1.15,
      collider: { width: 28, height: 26, offsetY: 14 },
    },
    {
      texture: "tree",
      x: 29,
      y: 18,
      scale: 1.12,
      collider: { width: 28, height: 26, offsetY: 14 },
    },
  ],
  labels: [
    { x: 6, y: 2, text: "Inn" },
    { x: 20, y: 2, text: "Guild" },
    { x: 24, y: 15, text: "Workshop" },
  ],
  npcs: [
    {
      id: "mira",
      name: "Mira",
      x: 8,
      y: 12,
      tint: 0xf4a261,
      dialog: "",
    },
    {
      id: "toren",
      name: "Toren",
      x: 14,
      y: 8,
      tint: 0x7bd389,
      dialog: "",
    },
    {
      id: "selin",
      name: "Selin",
      x: 23,
      y: 14,
      tint: 0x9d8df1,
      dialog: "",
    },
  ],
  pickups: [
    { id: "pickup-coin-east", itemId: "coin", amount: 8, label: "Coin Kesesi", texture: "pickupCoin", x: 17, y: 11 },
    { id: "pickup-coin-south", itemId: "coin", amount: 5, label: "Coin", texture: "pickupCoin", x: 9, y: 18 },
    { id: "pickup-key-west", itemId: "key", amount: 1, label: "Eski Anahtar", texture: "pickupKey", x: 4, y: 13 },
    { id: "pickup-gift-north", itemId: "giftBox", amount: 1, label: "Hediye Kutusu", texture: "pickupGiftBox", x: 20, y: 8 },
  ],
  chests: [
    { id: "chest-workshop", x: 26, y: 16 },
  ],
};
